name: queue_management
description: A Very Good Project created by Very Good CLI.
version: 1.0.1+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
